name: Push Username for Jenkins

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to check'
        required: true

jobs:
  commit-username:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # даём право на push в репозиторий
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Commit with username in message
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "check-user: ${{ github.event.inputs.username }}"
          git push
